### ISSUE TITLE
Can't find toolkit-path when "hekit build"

### ISSUE THREAD

**Issue by xhuan28** [intel/he-toolkit#145]
I setup build environment according to readme and then I tried to run "hekit build recipes/examples.toml". It prompts "Please enter toolkit-path: ", error "Error while running subcommand FileNotFoundError(2, 'No such file or directory')" after I entered the correct he-toolkit path. And I notice that in example.toml, there is a variable of "!toolkit-path!". Should I set it somewhere beforehand?

**Comment by jlhcrawford** [comment]
Hi @xhuan28, thank you for posting your issue.

I would like to ask for further information.
Firstly what platform/OS are you currently attempting to build on?
Have you installed the HE libraries (HElib, SEAL, etc.) and their dependencies specified in the `recipes/default.toml`?
Is there a specific example you are trying to build or do you want to build all of them?

Note: The `toolkit-path` should be the path to the top level of the he-toolkit project (i.e. `~/projects/he-toolkit`)

Thanks

**Comment by xhuan28** [comment]
Thanks for your reply. Yes, I need to install `recipes/default.toml` first before I build `recipes/examples.toml`.
