### ISSUE TITLE
gmp.h missing

### ISSUE THREAD

**Issue by sjain70** [intel/he-toolkit#148]
While running 'hekit install recipes/default.toml', i get following error. How do I fix it?

[BASH] sh MakeCheckFeatures "ALIGNED_ARRAY BUILTIN_CLZL LL_TYPE SSSE3 AVX PCLMUL AVX2 FMA AVX512F COPY_TRAITS1 COPY_TRAITS2 CHRONO_TIME MACOS_TIME POSIX_TIME AES_NI KMA" "g++ -I../include -I.  -g -O2 -pthread -march=native " "-lm"
[BASH] *** Checking for feature: ALIGNED_ARRAY [yes]
[BASH] *** Checking for feature: BUILTIN_CLZL [yes]
[BASH] *** Checking for feature: LL_TYPE [yes]
[BASH] *** Checking for feature: SSSE3 [yes]
[BASH] *** Checking for feature: AVX [no]
[BASH] *** Checking for feature: PCLMUL [no]
[BASH] *** Checking for feature: AVX2 [no]
[BASH] *** Checking for feature: FMA [no]
[BASH] *** Checking for feature: AVX512F [no]
[BASH] *** Checking for feature: COPY_TRAITS1 [yes]
[BASH] *** Checking for feature: COPY_TRAITS2 [yes]
[BASH] *** Checking for feature: CHRONO_TIME [yes]
[BASH] *** Checking for feature: MACOS_TIME [no]
[BASH] *** Checking for feature: POSIX_TIME [yes]
[BASH] *** Checking for feature: AES_NI [no]
[BASH] *** Checking for feature: KMA [no]
[BASH] make[1]: Leaving directory '/home/sandeep/.hekit/components/ntl/11.5.1/build/ntl-11.5.1/src'
[BASH] make setup3
[BASH] make[1]: Entering directory '/home/sandeep/.hekit/components/ntl/11.5.1/build/ntl-11.5.1/src'
[BASH] g++ -I../include -I.  -g -O2 -pthread -march=native   -o gen_gmp_aux gen_gmp_aux.cpp  -lgmp  -lm
[BASH] gen_gmp_aux.cpp:29:10: fatal error: gmp.h: No such file or directory
[BASH]    29 | #include <gmp.h>
[BASH]       |          ^~~~~~~
[BASH] compilation terminated.
[BASH] make[1]: *** [makefile:360: setup3] Error 1
[BASH] make[1]: Leaving directory '/home/sandeep/.hekit/components/ntl/11.5.1/build/ntl-11.5.1/src'
[BASH] make: *** [makefile:327: setup-phase] Error 2
Error while running subcommand
 BuildError("Function 'build' failed to execute external process")

==================
Tried installing gmp - which error'ed too

sandeep@sandeep-VirtualBox:~/he-toolkit$ sudo apt install gmp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gmp

**Comment by jlhcrawford** [comment]
Hi @sjain70 thank you for posting your issue.

I would like to ask, what OS/platform are you currently building HE Toolkit on?

To answer your question about GMP, it is a dependency of HElib and the instructions on how to build HElib's dependencies (more specifically GMP) can be found in the HElib documentation [here](https://github.com/homenc/HElib/blob/master/INSTALL.md#building-dependencies-for-option-2).

**Comment by jlhcrawford** [comment]
Closing this issue as there has been no response from the poster in 29 days after a request for more information.

Please reopen this issue or post a new one if there is an update.

Thanks
