### ISSUE TITLE
Update to SEAL v3.6.6

### ISSUE THREAD

**Issue by fboemer** [intel/he-toolkit#20]
See https://github.com/microsoft/SEAL/releases/tag/v3.6.6. This should yield benefits on CKKS ciphertext multiplication and CKKS ciphertext squaring.

**Comment by jlhcrawford** [comment]
This feature was reverted. SEAL version is still 3.6.5

**Comment by faberga** [comment]
@jlhcrawford - As we are now working on v1.3.0, we can move SEAL version up to 3.6.6.
Can you re-merge this feature, please?
Thanks.
-Flavio
