### ISSUE TITLE
build error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by xhuan28** [intel/he-toolkit#38]
Build env:
gcc: 11.1.0
g++: 11.1.0
cmake: 3.21.0

Error message:
he-toolkit/he-samples/build/ext_palisade/src/ext_palisade/third-party/google-benchmark/src/benchmark_register.h:22:30: error: ‘numeric_limits’ is not a member of ‘std’
   22 |   static const T kmax = std::numeric_limits<T>::max();
      
After including the header of <limits>, this build issue was fixed.

**Comment by jlhcrawford** [comment]
Hi, the error message you have posted seems to suggest that the issue is coming from the google-benchmark library https://github.com/google/benchmark which we are not the maintainers of.
